[workspace]
# wgpu requires the newer resolver
resolver = "2"
members = ["wgsl_bindgen", "example"]

[workspace.package]
version = "0.11.2"
authors = ["swoorup", "ScanMountGoat(Original Fork)"]
edition = "2021"
repository = "https://github.com/Swoorup/wgsl_bindgen"
license = "MIT"
documentation = "https://docs.rs/wgsl_bindgen"

[workspace.dependencies]
blake3 = "1.5.0"
bytemuck = "1.13"
case = "1.0"
colored = "2.1.0"
data-encoding = "2.5.0"
derivative = "2.2.0"
derive_builder = "0.20.0"
derive_more = "0.99.17"
encase = "0.7"
enumflags2 = "0.7.9"
futures = "0.3"
fxhash = "0.2.1"
glam = "0.27"
heck = "0.5"
include_absolute_path = "0.1"
indexmap = "2.2.3"
indoc = "2.0"
miette = "7.0.0"
naga = "0.19.0"
naga_oil = "0.13.0"
pathdiff = "0.2.1"
pretty_assertions = "1.2.1"
prettyplease = "0.2"
proc-macro2 = "1.0"
quote = "1.0"
regex = "1.10.3"
regex-syntax = "0.8.2"
smallvec = "1.13.1"
smol_str = "0.2.1"
strum = "0.26.1"
strum_macros = "0.26.1"
syn = "2.0"
thiserror = "1.0"
wgpu = "0.19"
wgpu-types = "0.19.0"
winit = "0.29"
